import json
import unittest
from types import SimpleNamespace
from unittest.mock import patch
from packaging.markers import default_environment

from src.engines.transitive_lookup import TransitiveLookup
from src.engines.relationship_resolver.pip_resolver import PipResolver


class PipParentLookupTest(unittest.IsolatedAsyncioTestCase):
    def test_pip_compile_comments_resolve_pinned_parents_without_pip(self):
        text = '''# autogenerated by pip-compile
fastapi==0.125.0
    # via -r requirements.in
fastapi-sqlalchemy==0.2.1
    # via -r requirements.in
starlette==0.50.0
    # via
    #   fastapi
    #   fastapi-sqlalchemy
anyio==4.15.0
    # via starlette
'''
        with patch("src.engines.relationship_resolver.pip_resolver.subprocess.run") as run:
            resolver = PipResolver.from_text(text)
            result = resolver.resolve("starlette")
            deeper = resolver.resolve("anyio")
        run.assert_not_called()
        self.assertEqual(result["version"], "0.50.0")
        self.assertEqual(result["introducers"], [
            {"package": "fastapi", "version": "0.125.0"},
            {"package": "fastapi-sqlalchemy", "version": "0.2.1"},
        ])
        self.assertEqual(deeper["introducers"], result["introducers"])

    async def test_starlette_parent_and_manifest_reuse(self):
        default_environment()  # Populate platform information before mocking subprocess.
        report = {"install": [
            {"requested": True, "metadata": {"name": "fastapi", "version": "0.115.0",
                "requires_dist": ["starlette>=0.37.2,<0.39.0"]}},
            {"requested": False, "metadata": {"name": "starlette", "version": "0.38.6"}},
            {"requested": True, "metadata": {"name": "unrelated", "version": "1.0",
                "requires_dist": ['starlette; python_version < "2"']}},
        ]}
        calls = []

        async def fetch(*args):
            calls.append(args)
            return "fastapi==0.115.0\n"

        items = [SimpleNamespace(package="starlette", ecosystem="pip", istransitive=True,
            vulnerabilities=[SimpleNamespace(manifest_path="requirements.txt")],
            dependency_occurrences=[], transitive_source_package=[]) for _ in range(2)]
        with patch("src.engines.relationship_resolver.pip_resolver.subprocess.run",
                   return_value=SimpleNamespace(stdout=json.dumps(report))) as run:
            await TransitiveLookup(SimpleNamespace(fetch=fetch)).populate("owner", "repo", items)
        self.assertEqual(len(calls), 1)
        run.assert_called_once()
        self.assertEqual(items[0].transitive_source_package, ["fastapi@0.115.0"])
        self.assertEqual(items[0].dependency_occurrences[0]["version"], "0.38.6")
        self.assertIn("--dry-run", run.call_args.args[0])
        self.assertIn("--only-binary=:all:", run.call_args.args[0])
